### PR TITLE
fix(io): replace std::fs in async fns with tokio::fs

### PR DESCRIPTION
**Pull request by twuebi**
This PR replaces blocking fs calls with async fs calls. Using blocking reads can cause unexpected hangs in async code https://ryhl.io/blog/async-what-is-blocking/

This does not address other blocking IO calls as they exist in e.g. `src/google/credential.rs:CredentialLoader::load_file` which may also be used in async contexts as changing these methods would be a breaking change.

### CODE REVIEW

**Comment by Xuanwo** [comment]
Thank you for this PR. However, some users of reqsign may have their own asynchronous runtime, which makes the introduction of `tokio::fs` potentially problematic. I am open to more suitable suggestions.

**Comment by twuebi** [comment]
Hi, thanks for the response, I think it should be possible to introduce cfg features for other async runtimes. Are you aware of users that require different runtimes apart from wasm targets at this time? 

In general, I think it is not a good idea to have blocking code run in async contexts in e.g. opendal or iceberg-rust, for people running single threaded runtimes it can be quite destructive and really hard to debug. On multi-threaded runtimes, it'll be even more subtle and seem random to a user.

**Comment by Xuanwo** [comment]
I think we can have a simple trait called `ReadFile` which can read all content in a `Vec<u8>`

```rust
#[async_trait]
trait ReadFile {
  async fn read_file(&self, path: &str) -> Result<Vec<u8>>
}
```

We can provide some default implementations for `tokio`. Users are free to create their own if needed.

**Comment by Xuanwo** [comment]
Thanks again for the PR. I'm going to close it now.

**Comment by twuebi** [comment]
I currently do not have the capacity to do such a large refactor of a library I do not know well. Doing blocking IO within async contexts can cause hard to debug issues and should be addressed. This can cause issues in depending crates such as opendal or iceberg-rust. I'll create an issue so that it doesn't fall off the map.

**Comment by Xuanwo** [comment]
Thanks!

**Pull request closed without merging**
